name: Build

on:
  push:
    branches: [ main, 'copilot/**' ]
  pull_request:
    branches: [ main ]

env:
  PLATFORM: Win32

jobs:
  build:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    # Opcional: descargar Nana si no está presente en el repo
    - name: Fetch Nana prebuilt (if not present)
      shell: pwsh
      env:
        NANA_URL: ${{ secrets.NANA_URL }} # p. ej., URL a un zip alojado en Releases o un hosting propio
      run: |
        if (!(Test-Path 'nana/build/bin')) { New-Item -ItemType Directory -Force -Path 'nana/build/bin' | Out-Null }
        if (!(Test-Path 'nana/build/bin/nana_v141_Release_x86.zip')) {
          if (-not $env:NANA_URL) { throw "NANA_URL secret is not set and nana_v141_Release_x86.zip is missing." }
          Invoke-WebRequest -Uri $env:NANA_URL -OutFile 'nana/build/bin/nana_v141_Release_x86.zip'
        }

    - name: Extract Nana library
      run: |
        cd nana/build/bin
        7z x nana_v141_Release_x86.zip
      shell: cmd

    - name: Build project
      run: |
        msbuild SDRunoPlugin_Template.vcxproj ^
          /p:Configuration=Release ^
          /p:Platform=${{ env.PLATFORM }} ^
          /p:PlatformToolset=v143 ^
          /p:AdditionalIncludeDirectories="include;nana\include" ^
          /p:AdditionalDependencies="nana\build\bin\nana_v141_Release_x86.lib;%(AdditionalDependencies)"
      shell: cmd

    - name: Package artifacts
      run: |
        mkdir artifacts
        copy Release\Cosmo.dll artifacts\ 2>nul || copy ${{ env.PLATFORM }}\Release\Cosmo.dll artifacts\ 2>nul || echo "DLL not found in expected location"
        7z a artifacts\Cosmo-${{ github.sha }}.zip Release\*.dll 2>nul || 7z a artifacts\Cosmo-${{ github.sha }}.zip ${{ env.PLATFORM }}\Release\*.dll 2>nul || echo "No DLLs to package"
      shell: cmd

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Cosmo-build-${{ github.sha }}
        path: artifacts/
